### ISSUE TITLE
Create a new "Release" with a concatenated consensus FASTA attached on each push?

### ISSUE THREAD

**Issue by niemasd** [andersen-lab/HCoV-19-Genomics#23]
I'm trying to pull all of the consensus genomes, but it takes forever to `git clone` or to download a zip file of the repo because of the large number of files. I understand the desire to have each consensus sequence in a separate file for the sake of `git push` friendliness (as well as to circumvent GitHub's file size limit), but would it be possible to add a GitHub Action to automatically create a new "Release" that includes a concatenated single-file FASTA attached to it upon every new commit?

As an example, the GitHub repo I use to track/store the LaTeX source of my CV has a GitHub Action that creates a new release, compiles the LaTeX source to PDF, and attaches the PDF to the release upon every single push:

https://github.com/niemasd/curriculum-vitae

The file that defines the GitHub Action can be found here:

https://github.com/niemasd/curriculum-vitae/blob/master/.github/workflows/compile.yml

I think you would just need to replace [LaTeX Compilation step](https://github.com/niemasd/curriculum-vitae/blob/master/.github/workflows/compile.yml#L9-L12) with a step that just runs `cat consensus_sequences/*.fasta > consensus_sequences.fasta` (or, ideally, `cat consensus_sequences/*.fasta | gzip -9 > consensus_sequences.fasta.gz` to compress), and then just edit the [Publish Release step](https://github.com/niemasd/curriculum-vitae/blob/master/.github/workflows/compile.yml#L21) to point to your `consensus_sequences.fasta.gz` file

I'm happy to help if desired!

**Comment by watronfire** [comment]
Sounds reasonable @niemasd. I've added the action you described.

**Comment by niemasd** [comment]
Perfect, works like a charm! Pro-tip that you can now hyperlink a permalink to the most up-to-date `consensus_sequences.gz` via the following URL:

https://github.com/andersen-lab/HCoV-19-Genomics/releases/latest/download/consensus_sequences.fasta.gz

Thanks for adding this so quickly!
