### ISSUE TITLE
consensus_sequences.fasta.gz are broken (empty)

### ISSUE THREAD

**Issue by niemasd** [andersen-lab/HCoV-19-Genomics#27]
I noticed that the `consensus_sequences.fasta.gz` files that are automatically created and attached are broken: they seem to just be empty files that were then gzipped (so they're 20 bytes overall). The last functional release seems to have been [SequenceUpload_2022.11.22_04-01](https://github.com/andersen-lab/HCoV-19-Genomics/releases/tag/SequenceUpload_2022.11.22_04-01), and then it was broken in [SequenceUpload_2022.12.03_01-21](https://github.com/andersen-lab/HCoV-19-Genomics/releases/tag/SequenceUpload_2022.12.03_01-21)

**Comment by niemasd** [comment]
I found the issue: the command `cat consensus_sequences/*.fasta` is getting the following error:

```
/usr/bin/cat: Argument list too long
```

because there are too many FASTA files. I'll fix the GitHub Action and submit a PR

**Comment by watronfire** [comment]
Commented in the wrong place. Thanks, Niema! Let me know if you run into any other issues.

**Comment by niemasd** [comment]
No problem! Will do; thanks!
